### ISSUE TITLE
Incompatibility with new allensdk API

### ISSUE THREAD

**Issue by rettigl** [AllenInstitute/mouse_connectivity_models#51]
Hi, the module seems to be incomatible to the new allensdk Cache API:

```
download/mouse_connectivity_models> pip install .
Processing /home/metis/download/mouse_connectivity_models
    ERROR: Command errored out with exit status 1:
     command: /home/metis/venv/conda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-34hlah93/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-34hlah93/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-req-build-34hlah93/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-34hlah93/setup.py", line 13, in <module>
        import mcmodels
      File "/tmp/pip-req-build-34hlah93/mcmodels/__init__.py", line 16, in <module>
        from . import core
      File "/tmp/pip-req-build-34hlah93/mcmodels/core/__init__.py", line 12, in <module>
        from .voxel_model_api import VoxelModelApi
      File "/tmp/pip-req-build-34hlah93/mcmodels/core/voxel_model_api.py", line 7, in <module>
        from allensdk.api.cache import cacheable, Cache
    ModuleNotFoundError: No module named 'allensdk.api.cache
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

```
>>> import allensdk
>>> import allensdk.api
>>> import allensdk.api.cache
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'allensdk.api.cache'
>>> allensdk.__version__
'2.10.2'
```

**Comment by kamdh** [comment]
But of course, Allen SDK breaks everything every few versions....
@DrJigsaw help?

**Comment by kamdh** [comment]
I have confirmed this issue.

**Comment by kamdh** [comment]
As a stopgap, you may install an older version such as 1.0.0 with
'pip install "allensdk=1.0.0"

**Comment by kamdh** [comment]
This is now addressed with https://github.com/AllenInstitute/mouse_connectivity_models/commit/03aef77a1a8dc69d6d48dbd889aa24d4c9b72ba0
