### ISSUE TITLE
mouse_connectivity_models cannot be installed

### ISSUE THREAD

**Issue by alex4200** [AllenInstitute/mouse_connectivity_models#57]
I am having problems to install the tool `mouse_connectivity_models` following the instructions given on the README. 

I am following the instructions to install that package on Ubuntu 20.04.3 and using pip version 22.0.3:

```
git clone https://github.com/AllenInstitute/mouse_connectivity_models.git
cd mouse_connectivity_models/
pip install .
```

But then I get the following error:
```

Processing /home/adietz/Local/1.22_NSE_Testing/mouse_connectivity_models
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/adietz/Local/1.22_NSE_Testing/mouse_connectivity_models/setup.py", line 13, in <module>
          import mcmodels
        File "/home/adietz/Local/1.22_NSE_Testing/mouse_connectivity_models/mcmodels/__init__.py", line 16, in <module>
          from . import core
        File "/home/adietz/Local/1.22_NSE_Testing/mouse_connectivity_models/mcmodels/core/__init__.py", line 8, in <module>
          from .base import VoxelData, RegionalData
        File "/home/adietz/Local/1.22_NSE_Testing/mouse_connectivity_models/mcmodels/core/base.py", line 13, in <module>
          import numpy as np
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I appreciate if that can be fixed

**Comment by kamdh** [comment]
Looks like you need to install numpy. Please look at the dependencies in the readme and make sure that those are installed.
